language: java
jdk:
  - oraclejdk7
  - openjdk7

sudo: false

cache:
  directories:
    - $HOME/.m2

install:
  - mvn package -P all-modules dependency:resolve -Dmaven.test.skip -Dmaven.javadoc.skip -Dcassandra.skip

script: 
  - mvn verify -Pcassandra-2.0 -Dmaven.javadoc.skip --quiet

after_success:
  - mvn jacoco:report jacoco:report-integration coveralls:report

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-v1.0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$API_KEY@github.com/rackerlabs/blueflood --tags

deploy:
  skip_cleanup: true
  provider: releases
  api_key: 
    secure: E1yPcauKBAbC81SyQxoBrCq4FzqChZLFDbHPIapkHA1XU2WZft8qBF8N17HfcV1hW3rhe13JioVtlVp3CPSVwF2KiQ7jd/Ukwzc97WYqHS+55h5+X+S8+AfspVO+VGoHNkbTzeF0q2dmlt45p8Xv8D1GJXYZB7DXrnegGyFfxf4=
  file_glob: true
  file:
    - "./blueflood-all/target/blueflood-all-2.0.0-SNAPSHOT-jar-with-dependencies.jar"
  on:
    repo: rackerlabs/blueflood
    tags: false
    branch: rax-release

notifications:
  irc: "irc.freenode.net#blueflood"
  email:
    recepients:
      - blueflood-discuss@googlegroups.com
